inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-require_tools
  - rubocop-i18n
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.4
  Exclude:
    - db/schema.rb
    - vendor/**/*

Style/RedundantReturn:
  Enabled: false

Metrics/MethodLength:
  Max: 100
  CountAsOne: ['array', 'hash', 'heredoc']
