inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-thread_safety
  - rubocop-require_tools
  - rubocop-i18n
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.4
  Exclude:
    - db/schema.rb
    - vendor/**/*
